export const getCommunitiesRequestTypes = {
  ALL: 'ALL',
  CREATED_BY_ME: 'CREATED_BY_ME',
  JOINED: 'JOINED',
  EXPLORE_COMMUNITIES: 'EXPLORE_COMMUNITIES',
  HOME_CHAT_COMMUNITIES: 'HOME_CHAT_COMMUNITIES'
};