const screenNames = {
  HOME: 'HOME',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  DASHBOARD_HOME: 'DASHBOARD_HOME',
  COMMUNITIES: 'COMMUNITIES'
};

export default screenNames;