const screenNames = {
  HOME: 'HOME',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  DASHBOARD_HOME: 'DASHBOARD_HOME',
  COMMUNITIES: 'COMMUNITIES',
  WALLET: 'WALLET',
  NOTIFICATIONS: 'NOTIFICATIONS',
  PROFILE: 'PROFILE',
  COMMUNITY_ROOM: 'COMMUNITY_ROOM',
  APP_STACK: 'APP_STACK',
  BOTTOM_TABS: 'BOTTOM_TABS'
};

export default screenNames;